FROM debian:12
RUN apt-get update && apt-get upgrade -y

# Install python
RUN apt-get install -y python3
RUN apt-get install -y python3-venv

#create a venv
RUN python3 -m venv /venv
# Enable venv
ENV PATH="/venv/bin:$PATH"

#load scripts
WORKDIR /app
COPY ./requirements.txt ./requirements.txt

#install requirements
RUN pip install -r /app/requirements.txt

COPY . .


# Run scripts
RUN pip install gunicorn
CMD gunicorn --bind 0.0.0.0 app:app
